language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

services:
  - memcached
  - mongodb
  - redis-server

before_script:
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source

script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/cache/master/travis

matrix:
  allow_failures:
    - php: hhvm
